<?php

return [
  'users' => [
    [
      'id' => 'USR-001',
      'name' => 'Kouamé Assi',
      'email' => 'kouame.assi@alogoto.ci',
      'role' => 'Porteur',
      'status_label' => 'Actif',
      'status_class' => 'status-approved approved',
      'joined_at' => '12 Jan 2025',
    ],
    [
      'id' => 'USR-002',
      'name' => 'Banque Atlantique',
      'email' => 'partenaires@banqueatlantique.ci',
      'role' => 'Institution',
      'status_label' => 'Vérifié',
      'status_class' => 'status-funded funded',
      'joined_at' => '08 Fév 2025',
    ],
    [
      'id' => 'USR-003',
      'name' => 'Seynabou Ndiaye',
      'email' => 's.ndiaye@alogoto.sn',
      'role' => 'Porteur',
      'status_label' => 'En revue',
      'status_class' => 'status-submitted submitted',
      'joined_at' => '17 Fév 2026',
    ],
    [
      'id' => 'USR-004',
      'name' => 'BOAD',
      'email' => 'portfolio@boad.org',
      'role' => 'Institution',
      'status_label' => 'Suspendu',
      'status_class' => 'status-late late',
      'joined_at' => '22 Nov 2024',
    ],
  ],
  'projects' => [
    [
      'id' => 'PRJ-001',
      'name' => 'Coopérative Cacao Abidjan',
      'carrier' => 'Kouamé Assi',
      'sector' => 'Agriculture',
      'amount' => 15000000,
      'status_label' => 'Approuvé',
      'status_class' => 'status-approved approved',
    ],
    [
      'id' => 'PRJ-004',
      'name' => 'Clinique Mobile Bamako',
      'carrier' => 'Mamadou Diallo',
      'sector' => 'Santé',
      'amount' => 25000000,
      'status_label' => 'En financement',
      'status_class' => 'status-funding funding',
    ],
    [
      'id' => 'PRJ-009',
      'name' => 'Transport Électrique Lomé',
      'carrier' => 'Kossi Agbeko',
      'sector' => 'Transport',
      'amount' => 40000000,
      'status_label' => 'Soumis',
      'status_class' => 'status-submitted submitted',
    ],
    [
      'id' => 'PRJ-013',
      'name' => 'Marketplace Artisanale',
      'carrier' => 'Aïcha Coulibaly',
      'sector' => 'Commerce',
      'amount' => 9000000,
      'status_label' => 'Refusé',
      'status_class' => 'status-rejected rejected',
    ],
  ],
  'disputes' => [
    [
      'project' => 'Coopérative Cacao Abidjan',
      'user' => 'Banque Atlantique',
      'type' => 'Décaissement retardé',
      'status_label' => 'Ouvert',
      'status_class' => 'status-late late',
      'date' => '04 Mar 2026',
    ],
    [
      'project' => 'Clinique Mobile Bamako',
      'user' => 'Mamadou Diallo',
      'type' => 'Document contesté',
      'status_label' => 'En médiation',
      'status_class' => 'status-submitted submitted',
      'date' => '27 Fév 2026',
    ],
    [
      'project' => 'Plateforme EdTech Dakar',
      'user' => 'Ecobank',
      'type' => 'Échéance non rapprochée',
      'status_label' => 'Résolu',
      'status_class' => 'status-approved approved',
      'date' => '20 Fév 2026',
    ],
  ],
  'audit_logs' => [
    [
      'user' => 'Admin principal',
      'action' => 'Validation du projet PRJ-001',
      'date' => '09 Mar 2026 - 08:10',
      'ip' => '102.54.18.12',
    ],
    [
      'user' => 'Banque Atlantique',
      'action' => 'Téléchargement du rapport mensuel',
      'date' => '09 Mar 2026 - 07:43',
      'ip' => '105.235.8.77',
    ],
    [
      'user' => 'Kouamé Assi',
      'action' => 'Ajout d’un document juridique',
      'date' => '08 Mar 2026 - 18:26',
      'ip' => '105.235.18.42',
    ],
    [
      'user' => 'BOAD',
      'action' => 'Mise à jour du portefeuille',
      'date' => '08 Mar 2026 - 14:58',
      'ip' => '154.72.20.11',
    ],
  ],
  'notifications' => [
    [
      'title' => 'Nouvelle inscription',
      'message' => 'Une nouvelle institution a demandé l’accès à la plateforme.',
      'time' => 'Il y a 15 min',
      'variant' => 'info',
    ],
    [
      'title' => 'Litige ouvert',
      'message' => 'Le projet Coopérative Cacao Abidjan a généré un nouveau litige.',
      'time' => 'Il y a 2 h',
      'variant' => 'warning',
    ],
    [
      'title' => 'Remboursement consolidé',
      'message' => 'Le flux de remboursements du jour a été rapproché avec succès.',
      'time' => 'Aujourd’hui',
      'variant' => 'success',
    ],
  ],
  'conversations' => [
    [
      'name' => 'Banque Atlantique',
      'role' => 'Institution financiere',
      'snippet' => 'Le comite d engagement souhaite confirmer le statut du projet PRJ-004.',
      'time' => '11:18',
      'unread' => 2,
      'active' => true,
      'avatar' => 'BA',
      'status' => 'En ligne',
    ],
    [
      'name' => 'Kouame Assi',
      'role' => 'Porteur de projet',
      'snippet' => 'Merci pour le retour, j ai bien recu la notification de validation.',
      'time' => '10:42',
      'unread' => 1,
      'active' => false,
      'avatar' => 'KA',
      'status' => 'Hors ligne',
    ],
    [
      'name' => 'Support conformite',
      'role' => 'Equipe interne',
      'snippet' => 'Le rapport KYC consolide est pret pour revue.',
      'time' => 'Hier',
      'unread' => 0,
      'active' => false,
      'avatar' => 'SC',
      'status' => 'En reunion',
    ],
  ],
  'messages' => [
    [
      'author' => 'Banque Atlantique',
      'time' => '11:02',
      'content' => 'Bonjour, pouvez-vous confirmer si le projet PRJ-004 peut passer en validation finale aujourd hui ?',
      'outgoing' => false,
      'status' => '',
    ],
    [
      'author' => 'Vous',
      'time' => '11:05',
      'content' => 'Oui, la revue documentaire est terminee. Le dossier peut etre soumis au comite cet apres-midi.',
      'outgoing' => true,
      'status' => 'Lu',
    ],
    [
      'author' => 'Banque Atlantique',
      'time' => '11:11',
      'content' => 'Parfait. Nous mettons a jour la note interne et revenons vers vous apres arbitrage.',
      'outgoing' => false,
      'status' => '',
    ],
  ],
  'profile' => [
    'user_id' => 'ADM-2026-001',
    'name' => 'Admin principal',
    'email' => 'admin@alogoto.com',
    'phone' => '+225 27 20 00 00 01',
    'role' => 'Administrateur plateforme',
    'team' => 'Supervision & conformite',
    'initials' => 'AP',
    'location' => 'Plateau, Abidjan',
    'joined' => 'Jan 2024',
    'bio' => 'Responsable du pilotage operationnel, de la gouvernance des utilisateurs et du suivi des alertes critiques ALOGOTO.',
  ],
  'sessions' => [
    [
      'user' => 'Admin principal',
      'device' => 'Chrome sur Windows 11',
      'ip' => '102.54.18.12',
      'status_label' => 'Active',
      'status_class' => 'status-approved approved',
      'time' => '09 Mar 2026 - 08:10',
    ],
    [
      'user' => 'Admin conformité',
      'device' => 'Safari sur macOS',
      'ip' => '102.54.18.42',
      'status_label' => 'Active',
      'status_class' => 'status-approved approved',
      'time' => '09 Mar 2026 - 07:55',
    ],
    [
      'user' => 'Admin support',
      'device' => 'Firefox sur Linux',
      'ip' => '102.54.18.61',
      'status_label' => 'Expirée',
      'status_class' => 'status-draft draft',
      'time' => '08 Mar 2026 - 22:14',
    ],
  ],
];
