<?php

return [
  'projects' => [
    [
      'id' => 'PRJ-012',
      'name' => 'Coopérative Cacao Abidjan',
      'sector' => 'Agriculture',
      'requested_amount' => 12000000,
      'risk_label' => 'Faible',
      'risk_class' => 'risk-badge risk-low',
      'quality_score' => 88,
      'risk_score' => 22,
      'estimated_roi' => 13.4,
      'recommendation' => 'Investir',
      'status_label' => 'Approuvé',
      'status_class' => 'status-approved approved',
      'institution' => 'Banque Atlantique',
      'carrier' => 'Kouamé Assi',
      'date' => '12 Jan 2026',
      'amount_invested' => 5000000,
      'validation_label' => 'En revue',
      'validation_class' => 'status-submitted submitted',
    ],
    [
      'id' => 'PRJ-015',
      'name' => 'Clinique Mobile Bamako',
      'sector' => 'Santé',
      'requested_amount' => 25000000,
      'risk_label' => 'Moyen',
      'risk_class' => 'risk-badge risk-medium',
      'quality_score' => 74,
      'risk_score' => 48,
      'estimated_roi' => 11.1,
      'recommendation' => 'Analyse complémentaire',
      'status_label' => 'Visible',
      'status_class' => 'status-visible submitted',
      'institution' => 'BOAD',
      'carrier' => 'Mamadou Diallo',
      'date' => '03 Fév 2026',
      'amount_invested' => 7200000,
      'validation_label' => 'À valider',
      'validation_class' => 'status-funding funding',
    ],
    [
      'id' => 'PRJ-018',
      'name' => 'Plateforme EdTech Dakar',
      'sector' => 'Technologie',
      'requested_amount' => 15000000,
      'risk_label' => 'Faible',
      'risk_class' => 'risk-badge risk-low',
      'quality_score' => 91,
      'risk_score' => 18,
      'estimated_roi' => 16.8,
      'recommendation' => 'Prioritaire',
      'status_label' => 'Approuvé',
      'status_class' => 'status-approved approved',
      'institution' => 'Ecobank',
      'carrier' => 'Seynabou Ndiaye',
      'date' => '18 Fév 2026',
      'amount_invested' => 9800000,
      'validation_label' => 'Validé',
      'validation_class' => 'status-approved approved',
    ],
    [
      'id' => 'PRJ-021',
      'name' => 'Transport Électrique Lomé',
      'sector' => 'Transport',
      'requested_amount' => 40000000,
      'risk_label' => 'Élevé',
      'risk_class' => 'risk-badge risk-high',
      'quality_score' => 61,
      'risk_score' => 69,
      'estimated_roi' => 9.2,
      'recommendation' => 'Refuser',
      'status_label' => 'Visible',
      'status_class' => 'status-visible submitted',
      'institution' => 'Banque Atlantique',
      'carrier' => 'Kossi Agbeko',
      'date' => '01 Mar 2026',
      'amount_invested' => 3500000,
      'validation_label' => 'Comité de risque',
      'validation_class' => 'status-late late',
    ],
  ],
  'repayments' => [
    [
      'project' => 'Coopérative Cacao Abidjan',
      'carrier' => 'Kouamé Assi',
      'amount' => 650000,
      'date' => '05 Mar 2026',
      'status_label' => 'Payé',
      'status_class' => 'status-approved approved',
    ],
    [
      'project' => 'Clinique Mobile Bamako',
      'carrier' => 'Mamadou Diallo',
      'amount' => 920000,
      'date' => '03 Mar 2026',
      'status_label' => 'En attente',
      'status_class' => 'status-submitted submitted',
    ],
    [
      'project' => 'Plateforme EdTech Dakar',
      'carrier' => 'Seynabou Ndiaye',
      'amount' => 780000,
      'date' => '28 Fév 2026',
      'status_label' => 'Payé',
      'status_class' => 'status-approved approved',
    ],
    [
      'project' => 'Transport Électrique Lomé',
      'carrier' => 'Kossi Agbeko',
      'amount' => 1250000,
      'date' => '20 Fév 2026',
      'status_label' => 'Retard',
      'status_class' => 'status-late late',
    ],
  ],
  'conversations' => [
    [
      'name' => 'Kouamé Assi',
      'role' => 'Porteur de projet',
      'snippet' => 'Le planning de décaissement a été mis à jour.',
      'time' => '10:24',
      'unread' => 1,
      'active' => true,
      'avatar' => 'KA',
    ],
    [
      'name' => 'Administrateur ALOGOTO',
      'role' => 'Supervision plateforme',
      'snippet' => 'Merci de confirmer la note de risque PRJ-021.',
      'time' => 'Hier',
      'unread' => 0,
      'active' => false,
      'avatar' => 'AD',
    ],
    [
      'name' => 'Seynabou Ndiaye',
      'role' => 'Porteur de projet',
      'snippet' => 'Le contrat fournisseur a été téléversé.',
      'time' => 'Hier',
      'unread' => 2,
      'active' => false,
      'avatar' => 'SN',
    ],
  ],
  'messages' => [
    [
      'author' => 'Kouamé Assi',
      'time' => '10:02',
      'content' => 'Bonjour, le bon de commande signé est désormais disponible dans l’espace documents.',
      'outgoing' => false,
    ],
    [
      'author' => 'Vous',
      'time' => '10:11',
      'content' => 'Parfait. Nous relançons l’équipe risque pour valider le prochain décaissement.',
      'outgoing' => true,
    ],
    [
      'author' => 'Kouamé Assi',
      'time' => '10:19',
      'content' => 'Très bien, merci. Je reste disponible pour tout complément.',
      'outgoing' => false,
    ],
  ],
  'notifications' => [
    [
      'title' => 'Nouveau projet disponible',
      'message' => 'Le projet Plateforme EdTech Dakar vient d’entrer dans votre pipeline de veille.',
      'time' => 'Il y a 20 min',
      'variant' => 'info',
    ],
    [
      'title' => 'Remboursement reçu',
      'message' => 'Coopérative Cacao Abidjan a réglé l’échéance du 05 Mar 2026.',
      'time' => 'Il y a 2 h',
      'variant' => 'success',
    ],
    [
      'title' => 'Message reçu',
      'message' => 'Kouamé Assi a confirmé le téléversement du bon de commande signé.',
      'time' => 'Aujourd’hui',
      'variant' => 'warning',
    ],
  ],
  'profile' => [
    'name' => 'Banque Atlantique',
    'email' => 'partenaires@banqueatlantique.ci',
    'phone' => '+225 27 20 25 30 40',
    'address' => 'Plateau, Abidjan, Côte d’Ivoire',
    'manager' => 'Aminata Touré',
    'initials' => 'BA',
    'type' => 'Institution financière',
  ],
];
