<?php

return [
  'projects' => [
    [
      'id' => 'PRJ-001',
      'name' => 'Cooperative Cacao Abidjan',
      'sector' => 'Agriculture',
      'description' => 'Extension de la chaine de transformation et achat de materiels de sechage.',
      'requested_amount' => 15000000,
      'funded_amount' => 11250000,
      'status_label' => 'En financement',
      'status_class' => 'status-funding funding',
      'created_at' => '05 Jan 2026',
      'duration' => '18 mois',
      'location' => 'Abidjan',
      'progress' => 75,
      'institution' => 'Banque Atlantique',
    ],
    [
      'id' => 'PRJ-002',
      'name' => 'Ferme Bio Bassam',
      'sector' => 'Agriculture',
      'description' => 'Industrialisation de la chaine de conditionnement et du stockage.',
      'requested_amount' => 8000000,
      'funded_amount' => 8000000,
      'status_label' => 'Finance',
      'status_class' => 'status-funded funded',
      'created_at' => '18 Dec 2025',
      'duration' => '12 mois',
      'location' => 'Grand-Bassam',
      'progress' => 100,
      'institution' => 'BOAD',
    ],
    [
      'id' => 'PRJ-003',
      'name' => 'Boutique Digitale Cocody',
      'sector' => 'Commerce',
      'description' => 'Lancement d une marketplace locale avec paiement mobile integre.',
      'requested_amount' => 5000000,
      'funded_amount' => 0,
      'status_label' => 'Brouillon',
      'status_class' => 'status-draft draft',
      'created_at' => '02 Mar 2026',
      'duration' => '9 mois',
      'location' => 'Cocody',
      'progress' => 0,
      'institution' => 'Aucune',
    ],
  ],
  'documents' => [
    [
      'name' => 'Business_plan_v3.pdf',
      'type' => 'Business Plan',
      'project' => 'Cooperative Cacao Abidjan',
      'status_label' => 'Valide',
      'status_class' => 'status-approved approved',
      'uploaded_at' => '04 Mar 2026',
    ],
    [
      'name' => 'Previsionnel_financier.xlsx',
      'type' => 'Financier',
      'project' => 'Cooperative Cacao Abidjan',
      'status_label' => 'En attente',
      'status_class' => 'status-submitted submitted',
      'uploaded_at' => '02 Mar 2026',
    ],
    [
      'name' => 'Attestation_fonciere.pdf',
      'type' => 'Legal',
      'project' => 'Ferme Bio Bassam',
      'status_label' => 'Valide',
      'status_class' => 'status-approved approved',
      'uploaded_at' => '25 Fev 2026',
    ],
    [
      'name' => 'Contrat_fournisseur.pdf',
      'type' => 'Contrat',
      'project' => 'Ferme Bio Bassam',
      'status_label' => 'Valide',
      'status_class' => 'status-approved approved',
      'uploaded_at' => '21 Fev 2026',
    ],
    [
      'name' => 'Maquette_plateforme.fig',
      'type' => 'Support produit',
      'project' => 'Boutique Digitale Cocody',
      'status_label' => 'A mettre a jour',
      'status_class' => 'status-draft draft',
      'uploaded_at' => '08 Mar 2026',
    ],
  ],
  'fundings' => [
    [
      'project' => 'Cooperative Cacao Abidjan',
      'institution' => 'Banque Atlantique',
      'amount' => 5000000,
      'date' => '12 Jan 2026',
      'status_label' => 'Decaisse',
      'status_class' => 'status-approved approved',
    ],
    [
      'project' => 'Cooperative Cacao Abidjan',
      'institution' => 'Ecobank CI',
      'amount' => 3250000,
      'date' => '04 Fev 2026',
      'status_label' => 'Confirme',
      'status_class' => 'status-funded funded',
    ],
    [
      'project' => 'Cooperative Cacao Abidjan',
      'institution' => 'BOAD',
      'amount' => 3000000,
      'date' => '28 Fev 2026',
      'status_label' => 'En analyse',
      'status_class' => 'status-submitted submitted',
    ],
    [
      'project' => 'Ferme Bio Bassam',
      'institution' => 'BOAD',
      'amount' => 8000000,
      'date' => '20 Dec 2025',
      'status_label' => 'Finance',
      'status_class' => 'status-funded funded',
    ],
    [
      'project' => 'Boutique Digitale Cocody',
      'institution' => 'NSIA Banque',
      'amount' => 1750000,
      'date' => '06 Mar 2026',
      'status_label' => 'Pre-accord',
      'status_class' => 'status-visible submitted',
    ],
  ],
  'repayments' => [
    [
      'project' => 'Ferme Bio Bassam',
      'amount' => 850000,
      'date' => '15 Jan 2026',
      'status_label' => 'Paye',
      'status_class' => 'status-approved approved',
      'institution' => 'BOAD',
    ],
    [
      'project' => 'Ferme Bio Bassam',
      'amount' => 850000,
      'date' => '15 Fev 2026',
      'status_label' => 'Paye',
      'status_class' => 'status-approved approved',
      'institution' => 'BOAD',
    ],
    [
      'project' => 'Ferme Bio Bassam',
      'amount' => 850000,
      'date' => '15 Mar 2026',
      'status_label' => 'En attente',
      'status_class' => 'status-submitted submitted',
      'institution' => 'BOAD',
    ],
    [
      'project' => 'Cooperative Cacao Abidjan',
      'amount' => 650000,
      'date' => '05 Jan 2026',
      'status_label' => 'Paye',
      'status_class' => 'status-approved approved',
      'institution' => 'Banque Atlantique',
    ],
    [
      'project' => 'Cooperative Cacao Abidjan',
      'amount' => 650000,
      'date' => '05 Fev 2026',
      'status_label' => 'Paye',
      'status_class' => 'status-approved approved',
      'institution' => 'Banque Atlantique',
    ],
    [
      'project' => 'Cooperative Cacao Abidjan',
      'amount' => 650000,
      'date' => '05 Mar 2026',
      'status_label' => 'En retard',
      'status_class' => 'status-late late',
      'institution' => 'Banque Atlantique',
    ],
  ],
  'conversations' => [
    [
      'name' => 'Banque Atlantique',
      'role' => 'Institution financiere',
      'snippet' => 'Nous attendons le bon de commande signe pour valider le prochain decaissement.',
      'time' => '09:20',
      'unread' => 2,
      'active' => true,
      'avatar' => 'BA',
    ],
    [
      'name' => 'Administrateur ALOGOTO',
      'role' => 'Support plateforme',
      'snippet' => 'Votre document legal a ete valide.',
      'time' => 'Hier',
      'unread' => 0,
      'active' => false,
      'avatar' => 'AA',
    ],
    [
      'name' => 'BOAD',
      'role' => 'Institution financiere',
      'snippet' => 'Merci de confirmer votre calendrier de remboursement.',
      'time' => 'Hier',
      'unread' => 1,
      'active' => false,
      'avatar' => 'BO',
    ],
    [
      'name' => 'Ecobank CI',
      'role' => 'Institution financiere',
      'snippet' => 'Votre demande passe en comite ce vendredi.',
      'time' => '06 Mar',
      'unread' => 0,
      'active' => false,
      'avatar' => 'EC',
    ],
  ],
  'messages' => [
    [
      'author' => 'Banque Atlantique',
      'time' => '09:12',
      'content' => 'Bonjour, pouvez-vous partager la derniere facture du fournisseur principal ?',
      'outgoing' => false,
    ],
    [
      'author' => 'Vous',
      'time' => '09:16',
      'content' => 'Bonjour, je viens de televerser la facture dans l espace documents.',
      'outgoing' => true,
    ],
    [
      'author' => 'Banque Atlantique',
      'time' => '09:19',
      'content' => 'Parfait. Nous verifions egalement le bon de commande signe.',
      'outgoing' => false,
    ],
    [
      'author' => 'Vous',
      'time' => '09:22',
      'content' => 'Le bon signe sera envoye cet apres-midi avec le planning logistique.',
      'outgoing' => true,
    ],
  ],
  'notifications' => [
    [
      'title' => 'Paiement recu',
      'message' => 'Le remboursement mensuel de Ferme Bio Bassam a ete confirme.',
      'time' => 'Il y a 30 min',
      'variant' => 'success',
      'icon' => 'bi-cash-coin',
    ],
    [
      'title' => 'Document valide',
      'message' => 'Le business plan de Cooperative Cacao Abidjan est maintenant valide.',
      'time' => 'Il y a 2 h',
      'variant' => 'info',
      'icon' => 'bi-file-earmark-check',
    ],
    [
      'title' => 'Nouveau financement',
      'message' => 'Ecobank CI a confirme 3,25M FCFA pour Cooperative Cacao Abidjan.',
      'time' => 'Aujourd hui',
      'variant' => 'warning',
      'icon' => 'bi-graph-up-arrow',
    ],
    [
      'title' => 'Message recu',
      'message' => 'Banque Atlantique vous a ecrit au sujet du prochain decaissement.',
      'time' => 'Aujourd hui',
      'variant' => 'muted',
      'icon' => 'bi-chat-dots',
    ],
    [
      'title' => 'Alerte echeance',
      'message' => 'Le remboursement du 15 Mar 2026 est encore en attente de validation.',
      'time' => 'Hier',
      'variant' => 'warning',
      'icon' => 'bi-calendar-check',
    ],
  ],
  'profile' => [
    'user_id' => 'PRT-2026-001',
    'name' => 'Kouame Assi',
    'email' => 'kouame.assi@alogoto.ci',
    'phone' => '+225 07 08 09 10 11',
    'organisation' => 'Cooperative Cacao Abidjan',
    'photo_initials' => 'KA',
    'location' => 'Abidjan, Cote d Ivoire',
    'joined' => 'Sept 2024',
    'role' => 'Porteur de projet',
    'bio' => 'Entrepreneur agricole specialise dans la transformation locale du cacao et les chaines courtes de distribution.',
  ],
  'security_logs' => [
    [
      'device' => 'Chrome sur Windows 11',
      'location' => 'Abidjan, CI',
      'ip' => '105.235.18.42',
      'time' => '09 Mar 2026 - 08:45',
      'status' => 'Session active',
      'status_class' => 'status-approved approved',
    ],
    [
      'device' => 'Safari sur iPhone',
      'location' => 'Abidjan, CI',
      'ip' => '105.235.18.51',
      'time' => '08 Mar 2026 - 20:14',
      'status' => 'Connexion reussie',
      'status_class' => 'status-funded funded',
    ],
    [
      'device' => 'Chrome sur MacOS',
      'location' => 'Lome, TG',
      'ip' => '154.72.14.90',
      'time' => '05 Mar 2026 - 11:27',
      'status' => 'A verifier',
      'status_class' => 'status-submitted submitted',
    ],
    [
      'device' => 'Firefox sur Windows 10',
      'location' => 'Dakar, SN',
      'ip' => '197.159.42.17',
      'time' => '27 Fev 2026 - 17:03',
      'status' => 'Expiree',
      'status_class' => 'status-draft draft',
    ],
  ],
];
